baseURL = "http://example.org/"
languageCode = "en-us"
title = "Дары Башкортостана"
canonifyUrls = "true"

[params]
    description = "Лучшие сувениры в Республике Башкортостан!"
    custom_css = ["css/local.css"]

[[params.social]]
        icon = "phone"
        url = "mailto:fpxg37@mail.ru"
[[params.social]]
    icon = "envelope-o"
    url = "mailto:fpxg37@mail.ru"
[[params.social]]
    icon = "twitter"
    url = "https://twitter.com/dantejohn"
[[params.social]]
    icon = "github"
    url = "https://github.com/dantejohn"
[[params.social]]
    icon = "instagram"
    url = "https://vk.com/dantejohn"
