baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
canonifyUrls = "true"

[params]
    description = "The best widgets in the world!"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:fpxg37@mail.ru"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/dantejohn"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/dantejohn"
[[params.social]]
    title = "instagram"
    icon = "instagram"
    url = "https://instagram.com/dantejohn"
